---
# roles/common/tasks/main.yml
- name: Disable swap
  ansible.builtin.command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Comment out swap entry in /etc/fstab
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^([^#].*\s+swap\s+.*)$'
    replace: '#\1'

- name: Disable SELinux temporarily
  ansible.builtin.command: setenforce 0
  ignore_errors: yes
  when: ansible_selinux.status == "enabled"

- name: Set SELinux to permissive permanently
  ansible.builtin.replace:
    path: /etc/selinux/config
    regexp: '^SELINUX=enforcing'
    replace: 'SELINUX=permissive'
  when: ansible_selinux.status == "enabled"

- name: Configure sysctl parameters
  ansible.builtin.copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.ipv4.ip_forward                 = 1
      net.bridge.bridge-nf-call-ip6tables = 1
    force: yes

- name: Apply sysctl settings
  ansible.builtin.command: sysctl --system

- name: Disable and stop firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: stopped
    enabled: no
    masked: yes

- name: Ensure pip is installed
  ansible.builtin.dnf:
    name: python3-pip
    state: present
  register: pip_installed
  check_mode: no

- name: Install required Python dependencies for Kubernetes
  ansible.builtin.pip:
    name:
      - kubernetes
      - pyyaml
    state: present
    executable: pip3
  when: pip_installed.changed
