- name: Register systems
  hosts: all
  become: yes
  vars:
    rhc_auth:
      login:
        username: "{{ lookup('env', 'RHC_USERNAME') }}"
        password: "{{ lookup('env', 'RHC_PASSWORD') }}"
    rhc_insights:
      state: absent
    rhc_release: "9.4"

  roles:
    - linux-system-roles.rhc
