---
- name: Revert Kubernetes Configuration on RHEL 9
  hosts: all
  become: yes
  tasks:

    - name: Unmask, enable, and start firewalld
      systemd:
        name: firewalld
        state: started
        enabled: yes
        masked: no

    - name: Remove sysctl parameters for Kubernetes
      file:
        path: /etc/sysctl.d/k8s.conf
        state: absent

    - name: Reload sysctl settings
      command: sysctl --system

    - name: Remove kernel modules persistence file
      file:
        path: /etc/modules-load.d/k8s.conf
        state: absent

    - name: Restore SELinux to enforcing mode
      replace:
        path: /etc/selinux/config
        regexp: '^SELINUX=permissive'
        replace: 'SELINUX=enforcing'

    - name: Enable SELinux immediately
      command: setenforce 1
      ignore_errors: yes

    - name: Uncomment swap entry in /etc/fstab
      replace:
        path: /etc/fstab
        regexp: '^#(.*\s+swap\s+.*)$'
        replace: '\1'

    - name: Enable swap
      command: swapon -a

    - name: Remove Docker repository
      command: dnf config-manager --set-disabled docker-ce-stable

    - name: Uninstall containerd
      dnf:
        name: containerd.io
        state: absent

    - name: Remove conatinerd config if exists
      file:
        path: /etc/containerd/config.toml
        state: absent

    - name: Uninstall Kubernetes components
      dnf:
        name:
          - kubeadm
          - kubelet
          - kubectl
        state: absent
        disable_excludes: kubernetes

    - name: Remove Kubernetes repository
      file:
        path: /etc/yum.repos.d/kubernetes.repo
        state: absent