---
galaxy_info:
  author: Jocke
  description: Install and configure containerd on RHEL-based systems.
  license: MIT
  min_ansible_version: 2.15
  platforms:
    - name: EL
      versions:
        - 9
  galaxy_tags:
    - container
    - containerd
    - docker
    - systemd

dependencies:
  - role: common