---
# tasks file for roles/kubernetes/master
- name: Check if Kubernetes repository is installed
  stat:
    path: /etc/yum.repos.d/kubernetes.repo
  register: kubernetes_repo

- name: Add Kubernetes repository
  yum_repository:
    name: kubernetes
    description: Kubernetes Repository
    baseurl: https://pkgs.k8s.io/core:/stable:/v1.32/rpm/
    gpgcheck: yes
    enabled: yes
    gpgkey:
      - https://pkgs.k8s.io/core:/stable:/v1.32/rpm/repodata/repomd.xml.key
    exclude:
      - kubelet
      - kubeadm
      - kubectl
      - cri-tools
      - kubernetes-cni
  when: not kubernetes_repo.stat.exists

- name: Install Kubernetes components
  dnf:
    name:
      - kubeadm
      - kubelet
      - kubectl
    state: present
    disable_excludes: kubernetes