---

- name: Reset Kubernetes component
  shell: "kubeadm reset --force --cri-socket=/var/run/{{ container_runtime }}/{{ container_runtime }}.sock"
  register: reset_cluster

- name: Join the worker node to the Kubernetes cluster
  command: "{{ hostvars['server101.joc.ke']['kube_join_cmd'] }}"
  when:
    - hostvars['server101.joc.ke']['kube_join_cmd'] is defined
  environment:
    no_proxy: "$no_proxy,.svc,.svc.cluster.local"
  notify:
    - Recreate kube-dns