---
# tasks file for roles/containerd
- name: Include installation tasks
  include_tasks: install.yml

- name: Include configuration tasks
  include_tasks: configure.yml

- name: Include service management tasks
  include_tasks: service.yml
