---
- name: Configure RHEL 9 for Kubernetes
  hosts: all
  become: yes
  roles:
    - pre_install
    - install_containerd
    - configure_containerd
    - install_kubernetes
    - configure_kubelet
  
- hosts: master
  gather_facts: yes
  become: yes
  roles:
    - { role: kubernetes/master, tags: master }
    - { role: cni, tags: cni }

- hosts: node
  gather_facts: yes
  become: yes
  roles:
    - { role: kubernetes/node, tags: node }