- name: Add Docker repository
  command: dnf config-manager --add-repo=https://download.docker.com/linux/rhel/docker-ce.repo

- name: Install containerd
  dnf:
    name: containerd.io
    state: present