- name: Disable swap
  command: swapoff -a

- name: Comment out swap entry in /etc/fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*\s+swap\s+.*)$'
    replace: '#\1'

- name: Disable SELinux temporarily
  command: setenforce 0
  ignore_errors: yes

- name: Set SELinux to permissive permanently
  replace:
    path: /etc/selinux/config
    regexp: '^SELINUX=enforcing'
    replace: 'SELINUX=permissive'

- name: Configure sysctl parameters
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.ipv4.ip_forward                 = 1
      net.bridge.bridge-nf-call-ip6tables = 1

- name: Apply sysctl settings
  command: sysctl --system

- name: Disable and stop firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: no
    masked: yes

- name: Ensure pip is installed
  dnf:
    name: python3-pip
    state: present

- name: Install required Python dependencies for Kubernetes
  pip:
    name:
      - kubernetes
      - pyyaml
    state: present
    executable: pip3

