name: Register with Red Hat
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: [self-hosted, Ansible]
      steps:
      - uses: actions/checkout@v4

      - name: Regsiter with Red Hat
        env:
          RHC_USERNAME: ${{ secrets.RHC_USERNAME }}
          RHC_PASSWORD: ${{ secrets.RHC_PASSWORD }}
        run: |
          ansible-playbook -i inventory.yml register.yml \
            --extra-vars "username=${RHC_USERNAME} password=${RCH_PASSWORD}"
