name: Register with Red Hat
on:
  workflow_dispatch:
jobs:
  ansible-playbook:
    runs-on:
      group: Ansible
    steps:
    - uses: actions/checkout@v4

    - name: Create Inventory File
      run: |
        echo "${{ secrets.ANSIBLE_INVENTORY }}" > inventory.ini
        chmod 600 inventory.ini  # ✅ Secure file permissions

    - name: Update and reboot systems
      run: |
        ansible-playbook -i inventory.ini update.yml
